"""changed foreign key in train travel times

Revision ID: 1d0f74ac4ddf
Revises: 52a38fce0f22
Create Date: 2025-04-16 23:10:23.297262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0f74ac4ddf'
down_revision: Union[str, None] = '52a38fce0f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'train_travel_times', ['train_route_id'])
    op.drop_constraint('train_travel_times_train_route_id_fkey', 'train_travel_times', type_='foreignkey')
    op.create_foreign_key(None, 'train_travel_times', 'full_routes', ['train_route_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'train_travel_times', type_='foreignkey')
    op.create_foreign_key('train_travel_times_train_route_id_fkey', 'train_travel_times', 'train_routes', ['train_route_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'train_travel_times', type_='unique')
    # ### end Alembic commands ###
