"""reworked travel times

Revision ID: 33a7e8fe3812
Revises: e300f3df344f
Create Date: 2025-05-10 21:33:06.526774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33a7e8fe3812'
down_revision: Union[str, None] = 'e300f3df344f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_travel_times', sa.Column('total_time', sa.Integer(), nullable=False))
    op.drop_column('train_travel_times', 'end_date')
    op.drop_column('train_travel_times', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_travel_times', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('train_travel_times', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('train_travel_times', 'total_time')
    # ### end Alembic commands ###
