"""added full routes model

Revision ID: 52a38fce0f22
Revises: 90b8d51c3a24
Create Date: 2025-04-15 23:43:25.426124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a38fce0f22'
down_revision: Union[str, None] = '90b8d51c3a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('full_routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('full_routes')
    # ### end Alembic commands ###
