"""added trains and distance in full routes

Revision ID: e300f3df344f
Revises: 1d0f74ac4ddf
Create Date: 2025-04-23 00:22:37.317204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e300f3df344f'
down_revision: Union[str, None] = '1d0f74ac4ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('full_routes', sa.Column('distance', sa.Float(), nullable=False))
    op.add_column('full_routes', sa.Column('train_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'full_routes', 'trains', ['train_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'full_routes', type_='foreignkey')
    op.drop_column('full_routes', 'train_id')
    op.drop_column('full_routes', 'distance')
    # ### end Alembic commands ###
