"""init all models

Revision ID: f1c8fc93cad3
Revises: 091c051264a1
Create Date: 2025-03-30 19:45:04.730572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c8fc93cad3'
down_revision: Union[str, None] = '091c051264a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('train_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('min_speed', sa.Float(), nullable=False),
    sa.Column('max_speed', sa.Float(), nullable=False),
    sa.Column('min_distance', sa.Float(), nullable=False),
    sa.Column('max_distance', sa.Float(), nullable=False),
    sa.CheckConstraint('max_speed > min_distance', name='max_distance_range_constraint'),
    sa.CheckConstraint('max_speed > min_speed', name='max_speed_range_constraint'),
    sa.CheckConstraint('min_speed > 0.0', name='min_distance_range_constraint'),
    sa.CheckConstraint('min_speed > 0.0', name='min_speed_range_constraint'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('train_routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('start_station_id', sa.Uuid(), nullable=False),
    sa.Column('end_station_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('distance > 0.0', name='distance_range_constraint'),
    sa.CheckConstraint('start_station_id != end_station_id', name='stations_not_equal_constraint'),
    sa.ForeignKeyConstraint(['end_station_id'], ['stations.id'], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(['start_station_id'], ['stations.id'], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_station_id', 'end_station_id', name='start_end_stations_unique_constraint')
    )
    op.create_table('trains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_number', sa.String(length=5), nullable=False),
    sa.Column('train_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['train_type_id'], ['train_types.id'], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_number')
    )
    op.create_table('train_travel_times',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('train_route_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('start_date != end_date', name='dates_not_equal_constraint'),
    sa.CheckConstraint('start_date < end_date', name='end_date_higher_start_date_constraint'),
    sa.ForeignKeyConstraint(['train_route_id'], ['train_routes.id'], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_travel_times')
    op.drop_table('trains')
    op.drop_table('train_routes')
    op.drop_table('train_types')
    op.drop_table('stations')
    # ### end Alembic commands ###
